### ISSUE TITLE
order of build in dist file not correct

### ISSUE THREAD

**Issue by borntorun** [tristanguigue/angular-dynamic-layout#11]
Causing the following error when including the js file:
Uncaught Error: [$injector:nomod] Module 'dynamicLayout' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.17/$injector/nomod?p0=dynamicLayout
REGEX_STRING_REGEXP @ angular.js:63
(anonymous function) @ angular.js:1778ensure @ angular.js:1702module @ angular.js:1776
(anonymous function) @ angular-dynamic-layout.js:5
(anonymous function) @ angular-dynamic-layout.js:18

The module('dynamicLayout'... in line 382 should be defined prior of filters and directives.
I think in the Gruntfile shoulb be specified the order for the concat operation.

**Comment by tristanguigue** [comment]
Thanks for the comment, this has now been fixed in https://github.com/tristanguigue/angular-dynamic-layout/releases/tag/0.1.10
