### ISSUE TITLE
The demo does not work with the Angular 1.4.4 release 

### ISSUE THREAD

**Issue by namitkabra** [tristanguigue/angular-dynamic-layout#15]
The angular-dynamic-layout demo @ http://tristanguigue.github.io/angular-dynamic-layout/ does not work with the latest Angular release. So is angular-dynamic-layout not compatible with Angular 1.4.4 ?

**Comment by tristanguigue** [comment]
I haven't tested with the latest version of Angular but I´m assuming that wouldn´t be too much changes to make it compatible. As an open-source project feel free to contribute with a Pull Request  otherwise I will try to have a look when I get the time.

**Comment by namitkabra** [comment]
Hi,

Thank you for answering. I am just getting used to JavaScript. I wish I was
competent enough to make that work with the new release. So I will wait
till you get time to make it work.

Regards,
Namit Kabra

**Comment by shamseerss** [comment]
https://github.com/tristanguigue/angular-dynamic-layout/pull/16

This is a quick fix to make it work on angular 1.4.4.

**Comment by williamnoto** [comment]
So should now work with 1.4.8 right?
