### ISSUE TITLE
Unsafe minification using ng-min or ng-annotate

### ISSUE THREAD

**Issue by koolshams** [tristanguigue/angular-dynamic-layout#17]
Good plugin. I am trying to use it in one of my projects.

Need to make the code minifier friendly. Now when i minify it it throws an error. To make minifier friendly. To make it minifier friendly code like
```
module.directive('directive1', directive1)
function directive1($scope){
}
```
Must be converted into 
```
module.directive('directive1', function($scope){}).
```

Do you have any plan for this. Any way i need this. Please comment so that i will submit a pull request.

Thanks

**Comment by tristanguigue** [comment]
Thanks, yes actually it was the case before [this](https://github.com/tristanguigue/angular-dynamic-layout/pull/9 ) was submitted. Feel free to make the changes to make it minification friendly once more.

**Comment by koolshams** [comment]
Pull request submitted. Please have a look. 
https://github.com/tristanguigue/angular-dynamic-layout/pull/18
I changed only where needed. Avoided too much changes. Please have a look. 

Thanks.
