### ISSUE TITLE
Can you please add license to your project?

### ISSUE THREAD

**Issue by anatoly314** [tristanguigue/angular-dynamic-layout#47]
Without explicit license your code can't be used in a proprietary software, please consider using Apache/MIT license. 
Thank you.

**Comment by tristanguigue** [comment]
The bower package does have an MIT license see https://github.com/tristanguigue/angular-dynamic-layout/blob/da929fb88851d7b2d7f13a22ffaadbb5ab82adac/bower.json#L21

Let me know if that's not enough.

**Comment by anatoly314** [comment]
Yes, it's enough. Thank you!
