### ISSUE TITLE
Add main files array to bower.json

### ISSUE THREAD

**Issue by dejavu1987** [tristanguigue/angular-dynamic-layout#5]
The main:[] is missing in bower.json can you add this? 
More about main files array
https://github.com/bower/bower.json-spec#main

**Comment by dejavu1987** [comment]
Also I think build the main js file to the root and unminified plus version numbers stripped off from filename.

**Comment by tristanguigue** [comment]
Thanks, I added the main property and the unminified version: https://github.com/tristanguigue/angular-dynamic-layout/commit/3664e03584657ce99be145008488dff6ec179f0b
Also the distribution files are in the `dist` folder rather than the root
