### ISSUE TITLE
How to add elements?

### ISSUE THREAD

**Issue by itonics-tbeauvais** [tristanguigue/angular-dynamic-layout#6]
Array.push() doesn't do anything when I am wanting to implement an infinite scroll.  Is there a better way to add elements?

**Comment by tristanguigue** [comment]
It should work just fine: take a look here: https://github.com/tristanguigue/angular-dynamic-layout/blob/gh-pages/app/app.js#L143

I use `unshift` but it works with `push` as well (I double checked).

So once you've defined your items in you controller as
````
$scope.items=[
   {template: 'template1.html'},
   {template: 'template2.html'}
]
````

And your html being
````<div dynamic-layout items="cards" ></div>`````

Doing ````$scope.item.push({template: 'template3.html'})```` will add the item to the DOM.

Feel free to show some a code sample where you have an issue or use a Fiddle: http://jsfiddle.net/
